//
//  ListGamesPresenter.swift
//  GameCenterCleanSwift
//
//  Created by Siyuan Guo on 12/13/18.
//  Copyright (c) 2018 Siyuan Guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListGamesPresentationLogic
{
  func presentSomething(response: ListGames.Something.Response)
}

class ListGamesPresenter: ListGamesPresentationLogic
{
  weak var viewController: ListGamesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListGames.Something.Response)
  {
    let viewModel = ListGames.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
