//
//  ListGamesInteractor.swift
//  GameCenterCleanSwift
//
//  Created by Siyuan Guo on 12/13/18.
//  Copyright (c) 2018 Siyuan Guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListGamesBusinessLogic
{
  func doSomething(request: ListGames.Something.Request)
}

protocol ListGamesDataStore
{
  //var name: String { get set }
}

class ListGamesInteractor: ListGamesBusinessLogic, ListGamesDataStore
{
  var presenter: ListGamesPresentationLogic?
  var worker: ListGamesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListGames.Something.Request)
  {
    worker = ListGamesWorker()
    worker?.doSomeWork()
    
    let response = ListGames.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
