//
//  ListCommentsPresenter.swift
//  GameCenterCleanSwift
//
//  Created by Siyuan Guo on 12/13/18.
//  Copyright (c) 2018 Siyuan Guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCommentsPresentationLogic
{
  func presentSomething(response: ListComments.Something.Response)
}

class ListCommentsPresenter: ListCommentsPresentationLogic
{
  weak var viewController: ListCommentsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListComments.Something.Response)
  {
    let viewModel = ListComments.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
