//
//  ListCommentsInteractor.swift
//  GameCenterCleanSwift
//
//  Created by Siyuan Guo on 12/13/18.
//  Copyright (c) 2018 Siyuan Guo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCommentsBusinessLogic
{
  func doSomething(request: ListComments.Something.Request)
}

protocol ListCommentsDataStore
{
  //var name: String { get set }
}

class ListCommentsInteractor: ListCommentsBusinessLogic, ListCommentsDataStore
{
  var presenter: ListCommentsPresentationLogic?
  var worker: ListCommentsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListComments.Something.Request)
  {
    worker = ListCommentsWorker()
    worker?.doSomeWork()
    
    let response = ListComments.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
